name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://192.168.1.6:8080"
        user: "Aishwarya"
        token: 11db3ff04cd6ddcc18292ffab37aff9f90
        job: "pipeline"
        command_timeout: 200m
      env:
           PORT: 8080
